### ISSUE TITLE
Array.forEach (<anonymous>) - Error...

### ISSUE THREAD

**Issue by OberfragGER** [djerik/MMM-HomeConnect#2]
Hi,

du some problem with MagicMirror i ran. Im not sure if this is the problem which leads later to a stopped magic mirror...

`pm2 log MagicMirror`

This show this here:

`
0|MagicMir |     at Array.forEach (<anonymous>)
0|MagicMir |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_helper.js:119:39
0|MagicMir | [11.01.2022 21:12.48.199] [ERROR] (node:950) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
0|MagicMir | [11.01.2022 21:12.48.200] [ERROR] (node:950) UnhandledPromiseRejectionWarning: Error: Required parameter haId is not provided
0|MagicMir |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/execute/index.js:254:13
0|MagicMir |     at Array.forEach (<anonymous>)
0|MagicMir |     at Object.buildRequest (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/execute/index.js:225:22)
0|MagicMir |     at Function.execute (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/execute/index.js:106:24)
0|MagicMir |     at Swagger.execute (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/index.js:77:20)
0|MagicMir |     at Object.get_settings (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/interfaces.js:41:22)
0|MagicMir |     at HomeConnect.command (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/home-connect-js/main.js:43:54)
0|MagicMir |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_helper.js:138:11
0|MagicMir |     at Array.forEach (<anonymous>)
0|MagicMir |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_helper.js:119:39
0|MagicMir | [11.01.2022 21:12.48.201] [ERROR] (node:950) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)

`

**Comment by djerik** [comment]
Not sure why - I don't have problems with any of my 8 appliances and the module. I might create a version with more logging in the weekend, but first:
Is it a new installation of MM and the module?
Or was it working initially?
What version of MM?
Which appliances do you have?

**Comment by OberfragGER** [comment]
Hi,

im thankful for your Module. It works and the mirror. But sometimes my MM crashes, so i looked into PM2 logs... Thats one error.

Later i found some other things. Maybe its electron related. I hoped that you see, whats the problem in this specific case is.
I set up MM with 2.17 and now it rund on 2.18 (regular update).

I have oven, hood, coffeemachine and cooker.
If you didnt have a clue... it okay for me to close this issue.

**Comment by OberfragGER** [comment]
Just an update about the error message:

`0|MagicMir | [13.01.2022 12:46.30.681] [ERROR] (node:5198) UnhandledPromiseRejec                                                                                                                                                             tionWarning: Error: Required parameter haId is not provided
0|MagicMir |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/sw                                                                                                                                                             agger-client/lib/execute/index.js:254:13
0|MagicMir |     at Array.forEach (<anonymous>)
0|MagicMir |     at Object.buildRequest (/home/pi/MagicMirror/modules/MMM-HomeCo                                                                                                                                                             nnect/node_modules/swagger-client/lib/execute/index.js:225:22)
0|MagicMir |     at Function.execute (/home/pi/MagicMirror/modules/MMM-HomeConne                                                                                                                                                             ct/node_modules/swagger-client/lib/execute/index.js:106:24)
0|MagicMir |     at Swagger.execute (/home/pi/MagicMirror/modules/MMM-HomeConnec                                                                                                                                                             t/node_modules/swagger-client/lib/index.js:77:20)
0|MagicMir |     at Object.get_settings (/home/pi/MagicMirror/modules/MMM-HomeCo                                                                                                                                                             nnect/node_modules/swagger-client/lib/interfaces.js:41:22)
0|MagicMir |     at HomeConnect.command (/home/pi/MagicMirror/modules/MMM-HomeCo                                                                                                                                                             nnect/node_modules/home-connect-js/main.js:43:54)
0|MagicMir |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_helper.js:                                                                                                                                                             138:11
0|MagicMir |     at Array.forEach (<anonymous>)
0|MagicMir |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_helper.js:                                                                                                                                                             119:39
0|MagicMir | [13.01.2022 12:46.30.682] [ERROR] (node:5198) UnhandledPromiseRejec                                                                                                                                                             tionWarning: Unhandled promise rejection. This error originated either by throwi                                                                                                                                                             ng inside of an async function without a catch block, or by rejecting a promise                                                                                                                                                              which was not handled with .catch(). To terminate the node process on unhandled                                                                                                                                                              promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https:/                                                                                                                                                             /nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
`

Maybe "Error: Required parameter haId is not provided" could be a hint...?

This is my config:

`	{
	  module: "MMM-HomeConnect",
	  position: "bottom_left",
	  config: {
		client_ID: "2Xxxxxxxxxxxxxxxxxxxxxxxx1B",
		client_Secret: "2706xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx79D1",
	  }
	},`

**Comment by Binog** [comment]
HEy, I do have the same (?) error. One the Mirror I only see: No active devices. Although 2 of em are running.

UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode)

**Comment by djerik** [comment]
I see the problem after upgrading MM. I hope to have fix within the weekend

**Comment by djerik** [comment]
It was bit of tough one. Biggest problem was from changed logic inside Swagger-js that was in mismatch to the structure of the Home Connect API. But other libraries where also legacy and I decided to clean up most of the legacy depencies. Please update or better; delete the existing folder and do a fresh git clone and npm install.

I would love to get some feecback - both good and bad about the module.
