### ISSUE TITLE
after update 

### ISSUE THREAD

**Issue by Binog** [djerik/MMM-HomeConnect#3]
on one device I get this, and the mirror does not show anything for a long time. But later on it show up. and Homeconnect said no active devices, which now its true. but not sure if it changes its status.

`0|mm  | [03.04.2022 13:33.33.131] [ERROR] (node:11742) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
0|mm  | [03.04.2022 13:33.33.135] [ERROR]
0|mm  | (node:11742) UnhandledPromiseRejectionWarning: Error: Required parameter haId is not provided
0|mm  |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/execute/index.js:254:13
0|mm  |     at Array.forEach (<anonymous>)
0|mm  |     at Object.buildRequest (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/execute/index.js:225:22)
0|mm  |     at Function.execute (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/execute/index.js:106:24)
0|mm  |     at Swagger.execute (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/index.js:77:20)
0|mm  |     at Object.get_status (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/interfaces.js:41:22)
0|mm  |     at HomeConnect.command (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/home-connect-js/main.js:44:54)
0|mm  |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_helper.js:130:11
0|mm  |     at Array.forEach (<anonymous>)
0|mm  |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_helper.js:119:39
0|mm  | [03.04.2022 13:33.33.137] [ERROR] (node:11742) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
0|mm  | [03.04.2022 13:33.33.140] [ERROR]
0|mm  | (node:11742) UnhandledPromiseRejectionWarning: Error: Required parameter haId is not provided
0|mm  |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/execute/index.js:254:13
0|mm  |     at Array.forEach (<anonymous>)
0|mm  |     at Object.buildRequest (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/execute/index.js:225:22)
0|mm  |     at Function.execute (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/execute/index.js:106:24)
0|mm  |     at Swagger.execute (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/index.js:77:20)
0|mm  |     at Object.get_settings (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/interfaces.js:41:22)
0|mm  |     at HomeConnect.command (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/home-connect-js/main.js:44:54)
0|mm  |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_helper.js:138:11
0|mm  |     at Array.forEach (<anonymous>)
0|mm  |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_helper.js:119:39
0|mm  | [03.04.2022 13:33.33.143] [ERROR]
0|mm  | (node:11742) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
0|mm  | [03.04.2022 13:33.33.147] [ERROR]
0|mm  | (node:11742) UnhandledPromiseRejectionWarning: Error: Required parameter haId is not provided
0|mm  |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/execute/index.js:254:13
0|mm  |     at Array.forEach (<anonymous>)
0|mm  |     at Object.buildRequest (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/execute/index.js:225:22)
0|mm  |     at Function.execute (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/execute/index.js:106:24)
0|mm  |     at Swagger.execute (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/index.js:77:20)
0|mm  |     at Object.get_status (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/interfaces.js:41:22)
0|mm  |     at HomeConnect.command (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/home-connect-js/main.js:44:54)
0|mm  |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_helper.js:130:11
0|mm  |     at Array.forEach (<anonymous>)
0|mm  |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_helper.js:119:39
0|mm  | [03.04.2022 13:33.33.151] [ERROR] (node:11742) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
0|mm  | [03.04.2022 13:33.33.153] [ERROR] (node:11742) UnhandledPromiseRejectionWarning: Error: Required parameter haId is not provided
0|mm  |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/execute/index.js:254:13
0|mm  |     at Array.forEach (<anonymous>)
0|mm  |     at Object.buildRequest (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/execute/index.js:225:22)
0|mm  |     at Function.execute (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/execute/index.js:106:24)
0|mm  |     at Swagger.execute (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/index.js:77:20)
0|mm  |     at Object.get_settings (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/swagger-client/lib/interfaces.js:41:22)
0|mm  |     at HomeConnect.command (/home/pi/MagicMirror/modules/MMM-HomeConnect/node_modules/home-connect-js/main.js:44:54)
0|mm  |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_helper.js:138:11
0|mm  |     at Array.forEach (<anonymous>)
0|mm  |     at /home/pi/MagicMirror/modules/MMM-HomeConnect/node_helper.js:119:39
0|mm  | [03.04.2022 13:33.33.156] [ERROR] (node:11742) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)`

**Comment by djerik** [comment]
Hi Binog.

Sorry for that, I was in progress of solving the problems for new installs where Swagger-js had breaking changes. All should be good, please to a clean clone and npm install.

I would love to get some feedback on the module; both good and bad.

**Comment by Binog** [comment]
running smoothly !!!!  

Thank You very much for that fast reply !!
