### ISSUE TITLE
Loading Appliances

### ISSUE THREAD

**Issue by Xenuzz** [djerik/MMM-HomeConnect#9]
Hello, I wanted to try out the module and I did everything exactly as described but I wasn't sure if I needed to install anything else.  My Magic Mirror just says Loading.  Thanks in advance
![Snapchat-1764392397](https://github.com/djerik/MMM-HomeConnect/assets/122729688/b1f91196-598b-49b1-8830-9253cb277bc7)
![Snapchat-1366635313](https://github.com/djerik/MMM-HomeConnect/assets/122729688/81311b93-3600-4115-ad4b-f6922b3edd00)

**Comment by rbrueckner82** [comment]
@Xenuzz same here, any solution?
